# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

TWITTER_CONSUMER_KEY: Ge8PTxiJYToqYncUv8IL9Q
TWITTER_CONSUMER_SECRET: ZE39HxCsXS0CZyZpYnCvXVuug7LqmXhCgb7QP9a6IM
TWITTER_OAUTH_TOKEN: 532554631-uS3yCGSsRBtbLf1w2apEudWQISSxVhpzBubYasB3
TWITTER_OAUTH_TOKEN_SECRET: NnEfhpsrUncr9DxxXhLopUuFTNOjFTSdSSWU6aYkoA

# TWITTER_CONSUMER_KEY=Ge8PTxiJYToqYncUv8IL9Q
# TWITTER_CONSUMER_SECRET=ZE39HxCsXS0CZyZpYnCvXVuug7LqmXhCgb7QP9a6IM
# TWITTER_OAUTH_TOKEN=532554631-uS3yCGSsRBtbLf1w2apEudWQISSxVhpzBubYasB3
# TWITTER_OAUTH_TOKEN_SECRET=NnEfhpsrUncr9DxxXhLopUuFTNOjFTSdSSWU6aYkoA
